# -*- coding: utf-8 -*-
"""TransferenciasPix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17sivJBjus4b8OU8mp6da4ZUIAhheikHQ
"""

import numpy as np
import pandas as pd
from google.colab import files

dataSet = pd.read_csv('/content/Transações_Pix.csv')

"""# **READ**

"""

dataSet.head(1-2)

dataSet.isnull().sum()

dataSet.dtypes

"""# **ALTER**

### Alterando os nomes das colunas
"""

dataSet = dataSet.rename(columns={"AnoMes": "Ano_Mes",
    "Municipio_Ibge": "Municipio_Codigo",
    "Municipio": "Municipio_Nome",
    "Estado_Ibge": "Estado_Codigo",
    "Estado": "Estado_Nome",
    "Sigla_Regiao": "Regiao_Sigla",
    "Regiao": "Regiao_Nome",
    "VL_PagadorPF": "Valor_Pagador_PF",
    "QT_PagadorPF": "Quantidade_Pagador_PF",
    "VL_PagadorPJ": "Valor_Pagador_PJ",
    "QT_PagadorPJ": "Quantidade_Pagador_PJ",
    "VL_RecebedorPF": "Valor_Recebedor_PF",
    "QT_RecebedorPF": "Quantidade_Recebedor_PF",
    "VL_RecebedorPJ": "Valor_Recebedor_PJ",
    "QT_RecebedorPJ": "Quantidade_Recebedor_PJ",
    "QT_PES_PagadorPF": "Quantidade_Pessoas_Pagador_PF",
    "QT_PES_PagadorPJ": "Quantidade_Pessoas_Pagador_PJ",
    "QT_PES_RecebedorPF": "Quantidade_Pessoas_Recebedor_PF",
    "QT_PES_RecebedorPJ": "Quantidade_Pessoas_Recebedor_PJ"})

"""### Formatando dados de Mês"""

dataSet['Ano_Mes'] = dataSet['Ano_Mes'].astype(str)
dataSet['Ano'] = dataSet['Ano_Mes'].str[:4] # separando os valores de ano e mês a partir dos strings
dataSet['Mes'] = dataSet['Ano_Mes'].str[4:6]

dataSet['Data'] = pd.to_datetime(dataSet['Ano'] + '-' + dataSet['Mes'] + '-01')

dataSet['Data'].head(1-2)

"""### Alterando os tipos"""

dataSet.dtypes

dataSet['Ano'] = dataSet['Ano'].astype(int)
dataSet['Municipio_Codigo'] = dataSet['Municipio_Codigo'].astype('Int64')
dataSet['Estado_Codigo'] = dataSet['Estado_Codigo'].astype('Int64')

colunas_quantidades = [
    'Quantidade_Pagador_PF', 'Quantidade_Pagador_PJ',
    'Quantidade_Recebedor_PF', 'Quantidade_Recebedor_PJ',
    'Quantidade_Pessoas_Pagador_PF', 'Quantidade_Pessoas_Pagador_PJ',
    'Quantidade_Pessoas_Recebedor_PF', 'Quantidade_Pessoas_Recebedor_PJ'
]

for col in colunas_quantidades:
    dataSet[col] = dataSet[col].astype(int)

"""# **DROP**

"""

dataSet = dataSet.drop(['Ano_Mes'], axis=1)

"""# **SAVE**"""

dataSet.to_csv('/content/Transações_Pix.csv', index=False)

files.download('/content/Transações_Pix.csv')